export const ROLE = {
    TECH_OWNER: 0,
    OWNER: 2,
    PSICOLOGO: 4,
    SECRETARIA: 6
};

export const NAV_PERMISSIONS = {
    // Solo Tech Owner y Owner
    MASTER: [ROLE.TECH_OWNER, ROLE.OWNER],
    // Tech Owner, Owner y Psicólogo
    PROFESSIONAL: [ROLE.TECH_OWNER, ROLE.OWNER, ROLE.PSICOLOGO],
    // Todos
    PUBLIC: [ROLE.TECH_OWNER, ROLE.OWNER, ROLE.PSICOLOGO, ROLE.SECRETARIA],
};

export const ACTION_PERMISSIONS = {
    CREATE_PATIENT: [ROLE.TECH_OWNER, ROLE.OWNER, ROLE.SECRETARIA, ROLE.PSICOLOGO],
    WRITE_CLINICAL_NOTES: [ROLE.TECH_OWNER, ROLE.OWNER, ROLE.PSICOLOGO],
    VIEW_PATIENTS_LIST: [ROLE.TECH_OWNER, ROLE.OWNER, ROLE.PSICOLOGO, ROLE.SECRETARIA],
};